name: Image Builds
on:
  push:
    branches:
      - master
      - dev
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image-name:
          - thechosenlan/transmission-openvpn
        include:
          - image-name: thechosenlan/transmission-openvpn
            context: ./
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # QEMU emulator to build for other platforms
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Buildx automates creating the multi-arch manifest build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Authenticate so that we can push to Docker Hub
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Generate image tags and labels
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ matrix.image-name }}
          tags: |
            type=edge
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      # Finally, build and push the images
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          platforms: linux/amd64,linux/arm,linux/arm64
          build-args: |
            REVISION=${{ github.sha }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow}}
